services:
    movie-collection:
        environment:
            - NODE_ENV=production
        container_name: movie-collection
        image: movie-collection
        restart: always
        build: .
        ports:
            # - "80:3000"
            - "3000:3000"
            # - "443:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo:latest
        # volumes:
        #   - ./data:/data/db
        ports:
            - "27018:27017"
